name: Bonjour
on:
  - push
jobs:
  lint_dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: Installer Hadolint
        run: |
          curl -L "https://github.com/hadolint/hadolint/releases/latest/download/hadolint-$(uname -s)-$(uname -m)" -o /usr/local/bin/hadolint
          chmod +x /usr/local/bin/hadolint
      - name: Linter le Dockerfile
        run: hadolint Dockerfile

  dire_bonjour:
    runs-on: ubuntu-22.04
    env:
      IMAGE_NAME: "esgicicd"
    steps:

      - uses: actions/checkout@v4 # Récupère le contenu du dépôt correspondant au commit du workflow en cours
      - run: docker image build --tag="${IMAGE_NAME}" ./
      - run: docker container run --volume="$(pwd)":/app "${IMAGE_NAME}" npm run lint
