name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    env:
      IMAGE_NAME: "esgicicd"
    steps:

      - uses: actions/checkout@v4 # Récupère le contenu du dépôt correspondant au commit du workflow en cours
      - run: docker image build --tag="${IMAGE_NAME}" ./
      - run: docker container run --volume="$(pwd)":/app "${IMAGE_NAME}" npm run lint
