name: Bonjour
on:
  push:
  pull_request:
    types:
      - closed

    
jobs:
  # lint_dockerfile:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Installer Hadolint
  #       run: |
  #         curl -L "https://github.com/hadolint/hadolint/releases/latest/download/hadolint-$(uname -s)-$(uname -m)" -o /usr/local/bin/hadolint
  #         chmod +x /usr/local/bin/hadolint
  #     - name: Linter le Dockerfile
  #       run: hadolint Dockerfile

  dire_bonjour:
    runs-on: ubuntu-22.04
    env:
      IMAGE_NAME: "cicdpaul"
    steps:

      - uses: actions/checkout@v4 # Récupère le contenu du dépôt correspondant au commit du workflow en cours
      - run: docker image build --tag="${IMAGE_NAME}" ./
      - run: docker container run --volume="$(pwd)":/app "${IMAGE_NAME}" npm run lint
  push_on_docker:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: "Login to Docker Hub"
        uses: docker/login-action@v3
        if: github.ref == 'refs/heads/main'
        with:
          username: "rommel25"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"
      - name: "Push if on `main`"
        uses: docker/build-push-action@v6
        if: github.ref == 'refs/heads/main'
        with:
          push: true
          context: ./
          tags: "rommel25/cicdpaul:${{ github.ref_name }}"
